trigger:
- dev

variables:
  - name: PythonMain
    value: '3.11'

stages:
- stage: 'Code_check'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'pylint'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PythonMain)'
      displayName: 'Use Python main version.'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
      displayName: 'Install dependencies'
    - script: |
        pylint pyinsteon
      displayName: 'pylint'
    - script: |
        flake8 pyinsteon
      displayName: 'flake8'
    - script: |
        black pyinsteon
      displayName: 'black'

- stage: 'Tests'
  jobs:
  - job: 'PyTest'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python38:
          python.version: '3.8'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
      displayName: 'Install dependencies'

    - script: |
        python -m unittest discover -v
        # Convert unittest output to JUnit XML format
        python -m xmlrunner discover -o test-reports
      displayName: 'Run and Convert Unit Tests'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: '**/test-reports/*.xml'
        testRunTitle: 'Unit Tests'
